version: '3.8'

services:

  neo4j:
    image: neo4j:latest
    container_name: neo4j_interview
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1;'" ]
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  app:
    build: .
    container_name: neo4j_app
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    command: ["java", "-jar", "/app/neo4jdb-app.jar"]
    ports:
      - "8080:8080"

volumes:
  neo4j_data:
