CREATE CONSTRAINT domain_title IF NOT EXISTS FOR (d:Domain) REQUIRE d.title IS UNIQUE;
CREATE CONSTRAINT topic_title IF NOT EXISTS FOR (t:Topic) REQUIRE t.title IS UNIQUE;
CREATE CONSTRAINT theme_title IF NOT EXISTS FOR (th:Theme) REQUIRE th.title IS UNIQUE;
CREATE CONSTRAINT question_title IF NOT EXISTS FOR (q:Question) REQUIRE q.title IS UNIQUE;
CREATE CONSTRAINT followup_question_title IF NOT EXISTS FOR (fq:FollowUpQuestion) REQUIRE fq.title IS UNIQUE;
